apiVersion: apps/v1
kind: Deployment
metadata:
  name: dmd-deployment
  namespace: flipper
  labels:
    app: dmd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dmd
  template:
    metadata:
      labels:
        app: dmd
    spec:
      containers:
        - name: dmd
          image: flipper-dmd:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dmd-service
  namespace: flipper
spec:
  selector:
    app: dmd
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30081
  type: NodePort