apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-deployment
  namespace: flipper
  labels:
    app: iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot
  template:
    metadata:
      labels:
        app: iot
    spec:
      containers:
        - name: mosquitto
          image: docker.io/hounga/flipper-iot:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1883
          livenessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: iot-service
  namespace: flipper
spec:
  selector:
    app: iot
  ports:
    - port: 1883
      targetPort: 1883
      protocol: TCP
  type: ClusterIP
